<?= $this->extend('layout') ?>
<?= $this->section('content') ?>
<?php $descriptions = ['products' => 'Campus favorites, everyday essentials. Keep every item in check.', 'customers' => 'Get to know the people behind every purchase.', 'staff' => 'The people who keep your campus store moving.']; ?>
<div class="page-heading"><div><span class="eyebrow">CAMPUS STORE / <?= strtoupper(esc($resource)) ?></span><h1><?= esc(ucfirst($resource)) ?><span class="heading-count"><?= $total ?></span></h1><p><?= $descriptions[$resource] ?></p></div><a class="button primary" href="<?= site_url($resource . '/new') ?>"><?= icon('plus') ?> Add <?= esc($singular) ?></a></div>
<div class="list-toolbar"><form class="search-form" action="<?= site_url($resource) ?>" method="get"><?= icon('search') ?><input type="search" name="q" aria-label="Search <?= esc($resource) ?>" value="<?= esc($q, 'attr') ?>" placeholder="Search <?= esc($resource) ?> by name..."><button type="submit" class="button small secondary">Search</button></form><span class="muted"><?= $q !== '' ? 'Search results' : 'All active ' . esc($resource) ?></span><?php if ($q !== ''): ?><a class="text-link" href="<?= site_url($resource) ?>">Clear search</a><?php endif ?></div>

<?php if (!$rows): ?><section class="panel empty-state"><?= icon($resource === 'products' ? 'box' : 'users') ?><h2><?= $q ? 'No matches found' : 'A fresh start' ?></h2><p><?= $q ? 'Try another name or clear your search.' : 'Add your first ' . esc($singular) . ' to get started.' ?></p><a class="button primary" href="<?= site_url($resource . '/new') ?>"><?= icon('plus') ?> Add <?= esc($singular) ?></a></section>
<?php elseif ($resource === 'products'): ?><div class="product-grid">
<?php foreach ($rows as $row): ?><article class="product-card">
<div class="product-visual"><a href="<?= site_url('products/' . $row['id'] . '/edit') ?>"><img src="<?= image_url($row['image']) ?>" alt="<?= esc($row['name'], 'attr') ?>"></a><span class="pill <?= (int) $row['stock_quantity'] === 0 ? 'out' : ((int) $row['stock_quantity'] <= 10 ? 'low' : 'available') ?>"><?= (int) $row['stock_quantity'] === 0 ? 'Out of stock' : ((int) $row['stock_quantity'] <= 10 ? 'Low stock' : 'In stock') ?></span></div>
<div class="product-info"><span class="product-code">PRD-<?= str_pad((string) $row['id'], 4, '0', STR_PAD_LEFT) ?></span><h2><?= esc($row['name']) ?></h2><div class="product-price"><strong><?= money($row['price']) ?></strong><span><?= esc($row['stock_quantity']) ?> units</span></div></div>
<div class="product-actions"><a class="text-link" href="<?= site_url('products/' . $row['id'] . '/edit') ?>"><?= icon('edit') ?> Edit product</a><form method="post" action="<?= site_url('products/' . $row['id'] . '/delete') ?>" data-confirm="Archive <?= esc($row['name'], 'attr') ?>? This removes it from checkout. Past sales will remain in history."><?= csrf_field() ?><button class="icon-button" title="Archive product" aria-label="Archive <?= esc($row['name'], 'attr') ?>"><?= icon('trash') ?></button></form></div>
</article><?php endforeach ?></div>
<?php else: ?><section class="panel table-scroll"><table><thead><tr><th><?= $resource === 'staff' ? 'Staff member' : 'Customer' ?></th><th><?= $resource === 'staff' ? 'Username' : 'Email' ?></th><th><?= $resource === 'staff' ? 'Access' : 'Phone' ?></th><th>Added</th><th class="right">Actions</th></tr></thead><tbody>
<?php foreach ($rows as $row): ?><tr><td><div class="person-cell"><?php if (!empty($row['avatar'])): ?><img class="avatar" src="<?= image_url($row['avatar']) ?>" alt=""><?php else: ?><span class="avatar"><?= esc(initials($row['full_name'])) ?></span><?php endif ?><span><strong><?= esc($row['full_name']) ?></strong><small><?= $resource === 'staff' && (int) $row['id'] === (int) session('user_id') ? 'You' : '#' . str_pad((string) $row['id'], 4, '0', STR_PAD_LEFT) ?></small></span></div></td>
<td><?= esc($resource === 'staff' ? '@' . $row['username'] : $row['email']) ?></td><td><?= $resource === 'staff' ? '<span class="pill available">Store staff</span>' : esc($row['phone'] ?: '—') ?></td><td><?= date('M d, Y', strtotime($row['created_at'])) ?></td>
<td><div class="row-actions"><a class="icon-button" aria-label="Edit <?= esc($row['full_name'], 'attr') ?>" title="Edit" href="<?= site_url($resource . '/' . $row['id'] . '/edit') ?>"><?= icon('edit') ?></a><?php if ($resource !== 'staff' || (int) $row['id'] !== (int) session('user_id')): ?><form method="post" action="<?= site_url($resource . '/' . $row['id'] . '/delete') ?>" data-confirm="Delete <?= esc($row['full_name'], 'attr') ?> from active <?= esc($resource) ?>? Past sales will remain in history."><?= csrf_field() ?><button class="icon-button" title="Delete" aria-label="Delete <?= esc($row['full_name'], 'attr') ?>"><?= icon('trash') ?></button></form><?php endif ?></div></td></tr><?php endforeach ?>
</tbody></table></section><?php endif ?>
<div class="pagination-wrap"><?= $pager->links() ?></div>
<?= $this->endSection() ?>

